import pytest

import deltares_coastal_structures_toolbox.functions.structural.stability_rock_rear.vangentpozueta2004 as vangentpozueta2004


@pytest.mark.parametrize(
    (
        "cot_alpha, cot_phi, gamma_f, gamma_f_Crest, S, Hs, Tmm10, Rc, Rc_rear, Bc, N_waves, rho_rock, Dn50_expected"
    ),
    (
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.555,
            ]
        ),
        (
            [
                2.5,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.725,
            ]
        ),
        (
            [
                3.0,
                3.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.469,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.55,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.690,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.55,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.600,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                4.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.495,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                6.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.696,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                12.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.870,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                4.5,
                5.0,
                4.0,
                1000,
                2650,
                0.651,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                4.5,
                4.0,
                1000,
                2650,
                0.563,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                6.0,
                1000,
                2650,
                0.535,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                2000,
                2650,
                0.588,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2850,
                0.524,
            ]
        ),
        (
            [
                3.0,
                2.0,
                0.47,
                0.47,
                2.0,
                5.0,
                10.0,
                5.0,
                5.0,
                4.0,
                1000,
                2650,
                0.544,
            ]
        ),
    ),
)
def test_Dn50_backward(
    cot_alpha,
    cot_phi,
    gamma_f,
    gamma_f_Crest,
    S,
    Hs,
    Tmm10,
    Rc,
    Rc_rear,
    Bc,
    N_waves,
    rho_rock,
    Dn50_expected,
):
    Dn50_calculated = vangentpozueta2004.calculate_nominal_rock_diameter_Dn50(
        cot_alpha=cot_alpha,
        cot_phi=cot_phi,
        gamma_f=gamma_f,
        gamma_f_Crest=gamma_f_Crest,
        S=S,
        Hs=Hs,
        Tmm10=Tmm10,
        Rc=Rc,
        Rc_rear=Rc_rear,
        Bc=Bc,
        rho_rock=rho_rock,
        N_waves=N_waves,
    )

    assert Dn50_calculated == pytest.approx(Dn50_expected, abs=1e-2)
